### ISSUE TITLE
How to get token details?

### ISSUE THREAD

**Issue by pramsden** [gitlab4j/gitlab4j-api#1034]
I am using a Group Access Token to allow read-only access to a GitLab repository in a desktop app.

I would like to fetch the expiry date of the token at runtime. It is possible to do this using gitlab4j?

The GitLab API seems to support it:

```
GET groups/:id/access_tokens/:token_id
```

**Comment by jmini** [comment]
Gitlab documentation: https://docs.gitlab.com/ee/api/group_access_tokens.html

Related PR: https://github.com/gitlab4j/gitlab4j-api/pull/963 to create access token.

**Comment by jmini** [comment]
Have a look at the PR https://github.com/gitlab4j/gitlab4j-api/pull/1035 (feel free to review it and give feedback)

---

You can use [jitpack](https://jitpack.io/) to test in advance:

I created a tag in my fork in my fork: [5.3.0-pr_1035](https://github.com/jmini/gitlab4j-api/releases/tag/5.3.0-pr_1035), to test the PR and have a fixed version created by jitpack.

**Usage with gradle:**

```gradle
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
        content {
            includeGroup "com.github.jmini"
        }
    }
}

dependencies {
    // ...
    implementation 'com.github.jmini:gitlab4j-api:3da62c6dcd'
    // ...
}
```

**Usage with maven:**

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.unblu</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>3da62c6dcd</version>
  </dependency>
  <!-- ... -->
</dependencies>
```

**Usage with jbang:**

The example script uses [Jbang](https://www.jbang.dev/) where loading the dependency is really easy. You just need to declare this dependency:

```java
//DEPS https://github.com/jmini/gitlab4j-api/tree/3da62c6dcd
```

Instead of:
```java
//DEPS org.gitlab4j:gitlab4j-api:5.3.0
```

And then Jbang does the work of adding the additional repository for you.
