### ISSUE TITLE
`GitLabForm` fails to handle lists of values properly, overriding earlier entries  

### ISSUE THREAD

**Issue by Malenczuk** [gitlab4j/gitlab4j-api#1213]
In version **6.0.0-rc.7**, the `GitLabForm` class has a method `withParam(String name, List<T> values, boolean required)` for handling lists of values. However, this method **overrides the previously added values in the list** when adding parameters to `formValues`. As a result, only the **last value** from the list is retained.

### Problematic Code  
```java
for (T value : values) {
    if (value != null) {
        formValues.put(name + "[]", value.toString());
    }
}
```
In the above code, `formValues.put()` is used. Since `Map` does not allow duplicate keys, each new value with the same key (`name + "[]"`) overrides the previous one.  

### Expected Behavior  
The method should **allow multiple values** for the same parameter (e.g., appending to a list instead of overwriting). This is required for correctly sending form or query parameters like `name[]=value1&name[]=value2`.

### Actual Behavior  
Only the last value from the list is added to `formValues`.  

---

### Steps to Reproduce  

1. Create an instance of `GitLabForm`.  
2. Call `withParam("names", Arrays.asList("value1", "value2", "value3"))`.  
3. Retrieve `getFormValues()` and check the result.  

**Sample Code:**  
```java
GitLabForm form = new GitLabForm();
form.withParam("names", Arrays.asList("value1", "value2", "value3"));
System.out.println(form.getFormValues());
```

**Actual Output:**  
```
{names[]=value3}
```

**Expected Output:**  
```
{names[]=[value1, value2, value3]}
```

**Comment by jmini** [comment]
This is very valuable feedback and probably introduced by the change made for this issue: https://github.com/gitlab4j/gitlab4j-api/issues/1067

I will try to look into this, if you know how to fix it, feel free to send a pull-request.

**Comment by jmini** [comment]
In `GitLabApiForm` the loop is correct and continue to work.

https://github.com/gitlab4j/gitlab4j-api/blob/28f43e5a72149ac76d5573de8b56d1eb5d950e31/gitlab4j-api/src/main/java/org/gitlab4j/api/GitLabApiForm.java#L139-L143

Tested with [`ProjectAccessTokenScript`](https://github.com/jmini/gitlab-experiments/blob/main/gitlab4j-test/ProjectAccessTokenScript.java) using:
```
jbang ProjectAccessTokenScript.java CREATE_PROJECT_ACCESS_TOKEN --project *** --tokenName test2 --scope API --scope READ_API --expiresAt 2024-12-25
```

---

The problem is `GitLabForm`:

https://github.com/gitlab4j/gitlab4j-api/blob/28f43e5a72149ac76d5573de8b56d1eb5d950e31/gitlab4j-models/src/main/java/org/gitlab4j/models/GitLabForm.java#L124-L128

Because `formValues` is a `Map<String, String>` when `MultivaluedMap<String, String>` was used before.

**Comment by jmini** [comment]
Can be reproduced with the [`GroupScript.java`](https://github.com/jmini/gitlab-experiments/blob/376a3cebbfe75cf5ca84df5a8239c236be03b3c0/gitlab4j-test/GroupScript.java) script:

```
jbang GroupScript.java GET_DESCENDANT_GROUPS --group <id> --skip <id1> --skip <id2> -v
```

Only one of the 2 groups is filtered `<id1>` and `<id2>` when two are expected
