### ISSUE TITLE
createPipeline with variable fails

### ISSUE THREAD

**Issue by SamerAdra** [gitlab4j/gitlab4j-api#354]
createPipeline with variables does not work.
GitLab's API documentation on this does not help, but I found a comment in an [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/49527) that seems to help. Rémy Coutable suggests passing in the ref and variables as URL parameters, even though it's a POST call. I tried it out and it does seem to work that way.

org.gitlab4j.api.GitLabApiException: The following fields have validation errors: variables.key, base

	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:319)
	at org.gitlab4j.api.PipelineApi.createPipeline(PipelineApi.java:254)

**Comment by gmessner** [comment]
@SamerAdra 
This has been fixed and integration tests have been added to verify it is working correctly. The fix is available in release 4.10.17.  Please verify and close this issue when you have time.

I ended up passing the data in the body of the POST.  Doing it as query params would have caused a lot of hacking to work around the unusual way the REST endpoint is expecting the data.  It was also the only to ensure that the keys and values are properly paired together.

I've also added a ```createPipeline()``` method that takes a ```List<Variable>``` parameter as a convenience:
```
public Pipeline createPipeline(Object projectIdOrPath, String ref, List<Variable> variables)
```

**Comment by gmessner** [comment]
@SamerAdra 
Just wondering if you have had a chance to verify this fix?

**Comment by SamerAdra** [comment]
Works as expected, thanks a million!
