### ISSUE TITLE
No internal commit id

### ISSUE THREAD

**Issue by nkiesel** [gitlab4j/gitlab4j-api#358]
the discussions API for a commit expects an internal commit id as parameter, but commits do not have such an internal id.

**Comment by gmessner** [comment]
@nkiesel 
You've discovered a bug in the GitLab API docs.  Take a look at:
https://docs.gitlab.com/ce/api/discussions.html#get-single-commit-discussion

In the documentation, they refer to ```commit_id``` as an integer, where it is actually the SHA (a String) for the commit.  The ```DiscussionsApi``` was developed from this documentation, so it is wrong.  

We will do an audit of ```DiscussionsApi``` and other classes in this library to change ```commit_id``` from an ```Integer``` to a ```String```.  Will let you know as soon as the fix is released.

**Comment by gmessner** [comment]
@nkiesel 
Wow, after doing a thorough review of the Discussions API at GitLab (https://docs.gitlab.com/ce/api/discussions.html) I have discovered that the documentation is very incorrect.  Not only is the commit ID referred to as an integer instead of a SHA, but the discussion ID is also.  The discussion ID is actually a SHA (String) for every type of discussion.  Additionally, the URLs for the commits discussions are completely wrong:

Documented:
````
/projects/:id/commits/:commit_id/discussions
````
This is missing "repository" in the path.

Should be:
```
/projects/:id/repository/commits/:commit_sha/discussions
```

I have verified this via Postman.  Amazing that the documentation has been wrong for years.  I will be submitting an issue and a PR to fix it at GitLab CE (https://gitlab.com/gitlab-org/gitlab-ce) in the next week or so.

**Comment by nkiesel** [comment]
Thanks for the update.

I use this API to find all the commits on which I commented.  Ideally, I would like to see which of these comments were unanswered, but the API (and also the underlying model) does not seem to logically link these comments.

I currently iterate over all commits within a time window and then iterate through all the comments for them looking for those where I am the author. Not particulary elegant or fast but the best I could come up given the API. I would be happy to share the code (written in Kotlin).

**Comment by gmessner** [comment]
@nkiesel 
I have fixed the problems related to the commit ID and discussion ID and release 4.11.2.  You can find the changes in PR #359 if you'd like to take a look.  When you have time, please verify and close this issue.

Just to clarify, though you may already know this:
Comments are different than discussions, a discussion is basically a thread of comments, and are created and listed using different APIs.  If you look at a commit in the GitLab UI you'll see a section at the bottom, those are discussions, if you mouse over the actual commit, you'll see a comment hover-over that allows a comment to be added.

Use the ```CommitsApi``` to list the comments for a commit, and the ```DiscussionsApi``` to list the discussions for a commit.  Here are the methods for listing comments in the ```CommitsApi```:
```
public List<Comment> getComments(Object projectIdOrPath, String sha)
public Pager<Comment> getComments(Object projectIdOrPath, String sha, int itemsPerPage)
public Stream<Comment> getCommentsStream(Object projectIdOrPath, String sha)
```

BTW, I have found an issue already created for the ```commit_id``` vs. ```commit_sha``` and repository missing from the URL in the Discissions API docs:
https://gitlab.com/gitlab-org/gitlab-ce/issues/52755

I will fix the GitLab CE documentation and submit the PR to the GitLab-CE repo sometime next week.

**Comment by gmessner** [comment]
@nkiesel 
Can you verify this is fixed and close this issue?

**Comment by nkiesel** [comment]
thanks for the fix; I tried this locally and worked for me
