### ISSUE TITLE
Cannot setup default branch

### ISSUE THREAD

**Issue by bdpqll** [gitlab4j/gitlab4j-api#378]
![image](https://user-images.githubusercontent.com/43171515/59144217-213e0080-89dd-11e9-99ab-b2ccf5174bee.png)
![image](https://user-images.githubusercontent.com/43171515/59144240-7a0d9900-89dd-11e9-9519-d8dc78386423.png)

Thanks in advance!

**Comment by gmessner** [comment]
@bdpqll 
Unfortunately, this is a bug with the GitLab API, not this library.  You cannot set a default branch unless it exists and a branch cannot be set on an empty repo.  Even if you initialize the project with a readme (using the ```initialize_with_readme```) the default branch is still ignored. 

The API docs at https://docs.gitlab.com/ee/api/projects.html#create-project need to be updated and remove the ```default_branch``` setting from the create attributes.  I suggest you file a bug with GitLab concerning this.

In order to set the default branch, you will need to first create the project with a readme, create the ```develop``` branch on that project, and then use ```updateProject()``` to set the default branch.

**Comment by bdpqll** [comment]
Thanks a lot!
