### ISSUE TITLE
API call to get Groups Webhooks

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#393]
GitLab API has requests for webhooks on projects but they do not have api calls on groups webhooks. Group webhooks are only provided in the EE GitLab versions.

There is an issue stalled in GitLab to provide support for this api request. https://gitlab.com/gitlab-org/gitlab-ee/issues/2792

There is a workaround using https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/21645#note_157793041

Wondering if there is a way we can implement this in `gitlab4j`?

**Comment by gmessner** [comment]
@baymac 
This is not possible until GitLab adds an API for it.

Just wondering, do you know what type of webhook events are fired for groups?

**Comment by baymac** [comment]
For jenkins I am trying to add Folder Organisation support. In that you just select a group or a user and all its projects get indexed and built by Jenkins server. The group webhooks works the same way as project webhooks only difference is it will be get triggered for the enabled events in any of the projects inside the group.

**Comment by baymac** [comment]
It is similar to webhooks in GitHub Organisation.

**Comment by gmessner** [comment]
@baymac 
Until they add support for the Group Webhook API, to get that functionality you are going to need to get the projects for the group and do it per project.  I know it is not ideal but it is an option.

The other approach you could potentially use is to script the Group Webhook web page.  Take a look at what I did to create personal access tokens (AccessTokenUtils), which basically scripts the access token webpage in the GitLab web app.  You could use this approach to do the group webhook stuff.  The problem is that this is a very fragile approach as it can break with simple changes to the web page.

**Comment by baymac** [comment]
I will prefer using the per project basis until they add support. I think it is in their future planned feature. Although I checked out `AccessTokenUtils` code and its very nice hack. Learnt a new thing today.
