### ISSUE TITLE
Adding some description for compatibility with different Gitlab versions may be better

### ISSUE THREAD

**Issue by depay** [gitlab4j/gitlab4j-api#400]
Adding some description for compatibility with different Gitlab versions may be better. Not only for users working with API but also for them with WebHookManager since Jackson Date converter changes a lot for versions. Maybe there are more tricks for them.

e.g. I'm working with Gitlab 9.5 and tried a lot with gitlab4j-api 4.10/4.11, finally found 4.9.23 is the last version suitable for my web hook format..

**Comment by gmessner** [comment]
@depay 
Unfortunately, the version of GitLab you are using is 2 years old and much has changed with GitLab in those two years. One of them is that with GitLab version 11.0  they completely removed support for version 3 of the API and the Webhook stuff changed significantly.   GitLab also changes many things at the API level without saying anything, making it very difficult if not impossible to keep this library working correctly with really old versions of GitLab.

Because of the drastic changes at GitLab 11.0, I will add something to the documentation that indicates that current versions of this library only supports GitLab versions 11.0 and newer (GitLab 11.0 is over a year old).  To support users like yourself,  I will also include a recommendation that if a user is forced to use old versions of GitLab, it is recommended that you use a version of this library that was released just after the version of GitLab being used.

Just a recommendation, if at all possible it is simply good practice to keep application software updated, mainly because of security concerns, using such an old version of GitLab is absolutely exposing you to lots of security vulnerabilities.

**Comment by depay** [comment]
@gmessner  thanks for your reply . Upgrading a widely-used Gitlab is always not that easy, lolllll. Looking forward your new document :laughing:

**Comment by gmessner** [comment]
@depay 
I have updated the README.md with version support info.

In response to your upgrading comment.  You are right, upgrading is always more difficult when major versions are involved, and the version you are using (9.5) is now 3 full major versions behind, as GitLab 12.0 was recently released, so I'm sure it would be a major undertaking.

GitLab minor version releases should be treated as patches, and are typically pretty easy to install, also if you keep up to date with the minor version updates the major version updates are usually easier than if you do not.

I've been working with GitLab since late 2013 (I believe it was at 6.4), and have updated about 36 different installs of GitLab since then, following the minor release = patch release practice has really helped me when the major release updates needed to be done.

I know this may seem rigid, but I really do not want to do anything to GitLab4J-API that makes it easy to use old versions of GitLab, it is just not a good practice to be helping people use a piece of software that has security vulnerabilities and other bugs.  It also uses valuable resources that should be used to help move GitLab4J-API forward.  This is why I suggest using an old version of GitLab4J-API that matches.

**Comment by depay** [comment]
@gmessner  Got it and thanks. I'll close this one.
