### ISSUE TITLE
Missing username parameter in PushEvent

### ISSUE THREAD

**Issue by baymac** [gitlab4j/gitlab4j-api#416]
Here's an example of demo pushEvent:

```javascript
{
  ...
  "user_name": "John Smith",
  "user_username": "jsmith",
  ....
```
There are 2 fields a user name and a user username. GitLab4J only fetches `user name`.

**Comment by gmessner** [comment]
@baymac 
The field has been added and tested.  

BTW, all the events were just verified a few months back, they added this one since then, I'm thinking about asking GitLab to see if they can keep a change log to report changes to any API messages, would be a lot easier to stay on top of them.

Will probably be a few days for a release to be done, will let you know when it happens.

**Comment by baymac** [comment]
@gmessner Thanks. Agree that API changelog support from GitLab should be there.

**Comment by gmessner** [comment]
@baymac FYI, 4.11.19 has been released with this in it
