### ISSUE TITLE
Content-length cannot be null

### ISSUE THREAD

**Issue by TamasNeumer** [gitlab4j/gitlab4j-api#430]
Hi!

I have GitLab deployed in the Google cloud and apparently gitlab4j-api tries to do POST requests without a `Content-Length` header specified. (I was trying to add a tag to a commit.)

In the response I get: Error 411 (Length Required)!

I tried the very same request from Postman, and as postman adds `-H 'Content-Length: ' \`  to the request, the call succeeded.

Now if I'm not mistaken the fix should be in the ` protected Invocation.Builder invocation(URL url, MultivaluedMap<String, String> queryParams, String accept)` method right? Next to the auth headers the content-length should be also set?

Thank you in advance!

**Comment by gmessner** [comment]
@TamasNeumer 
This library uses the Jersey Client for HTTP communication which automatically puts the Content-Length header on POST requests. So that was not the problem.  And adding it to the ```invocation()``` method would not have been the solution either, as the content is not even available at that point.

What you have helped me discover was that the ```createTags()``` method was using query params instead of form data to create the tags, so there was no content and thus Content-Length was not set.

A release with this fix will be done in the next day or two, will let you know when it is available.

**Comment by TamasNeumer** [comment]
@gmessner 

Amazing, thank you!

**Comment by gmessner** [comment]
@TamasNeumer This fix has been released and is available in 4.12.2.

Please verify and close this issue when you have time.

**Comment by TamasNeumer** [comment]
Problem solved. Thank you for the quick fix!
