### ISSUE TITLE
Missing Merge request approvals API

### ISSUE THREAD

**Issue by alexmnyc** [gitlab4j/gitlab4j-api#470]
https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-the-approval-state-of-merge-requests

**Comment by gmessner** [comment]
@alexmnyc 
In addition to the one identified there are about 10 more related API calls that need to be implemented.  I will do this over the next week or so.

**Comment by gmessner** [comment]
@alexmnyc 
I have identified the following 6 endpoints that still need to be implemented, I'll go ahead and implement the deprecated methods and mark them deprecated.  I'm doing this because the replacements are very new (12.3).  Will this meet your needs or would I be OK to just implement the new Approval Rules API endpoints?

**Deprecated API endpoints**
[Change approval configuration](https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-approval-configuration)
[Change allowed approvers for Merge Request](https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-allowed-approvers-for-merge-request)

**Approval Rules API Endpoints - New as of GitLab 12.3 Starter and above**
[Get the approval state of merge requests](https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-the-approval-state-of-merge-requests)
[Get merge request level rules](https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-merge-request-level-rules)
[Create merge request level rule](https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-merge-request-level-rule)
[Update merge request level rule](https://docs.gitlab.com/ee/api/merge_request_approvals.html#update-merge-request-level-rule)

**Comment by gmessner** [comment]
@alexmnyc 
This functionality has been released.  I did not have time to thoroughly test it so if you could that would be great.  I will add integration tests next release.  Please verify and close when you have time.

**Comment by gmessner** [comment]
@alexmnyc 
Since this functionality has been released I'm closing this issue, if you find any problems with the implementation please feel free to reopen.
