### ISSUE TITLE
Branches API not available in Gitlab4J

### ISSUE THREAD

**Issue by ribardo0** [gitlab4j/gitlab4j-api#551]
Hi,

Branches API (https://docs.gitlab.com/ee/api/branches.html) is not available in Gitlab4J (only protected_branches API), we cannot list branches on a project.

Olivier

**Comment by ribardo0** [comment]
In fact after double checking I found it in RepositoryAPI, I guess this issue is not valid. The question that remain is : how do we find the correct API Java class when reading gitlab API documentation ?

**Comment by gmessner** [comment]
@ribardo0 The Branches API used to be part of the Repositories API, sometime in the last 4 years GitLab split up the documentation page for the Branches API.

What this library does is include links to the implemented GitLab API(s) in the Javadocs for the API classes.  I just added this to the ```RepositoryApi``` class.  Some day when I have time I will be creating a chart in the README.md that shows the mapping of the GitLab API to the API class that implements it.

For now, if you are having trouble finding the API class you can search for the URL provided in the GitLab documentation, this works because the method Javadocs include it, So if you wanted to find the Branches API you would search for the following string:
```
GET /projects/:id/repository/branches
```

**Comment by daleyzou** [comment]
Thanks, it solved my problem. Originally  project api moved the place
