### ISSUE TITLE
Add java9+ and Jakarta EE Support

### ISSUE THREAD

**Issue by walnut-tom** [gitlab4j/gitlab4j-api#894]
Add java9+ and Jakarta EE Support?

**Comment by Korde-vaibhav** [comment]
When can this release be expected ?

**Comment by BenderRodrigez** [comment]
Just come here while resolving my issues related to Spring 3 migration. Is there a way to use snapshot version?

**Comment by gedeffe** [comment]
Hello,

As we are moving our projects to new version of Spring Boot (3.x), it implies also a move to JEE (jakarta).
Feel free to comment related PR (#943) which has been successfully tested locally with our use of gitlab api ^^

Have a nice day
Gedeffe

**Comment by jmini** [comment]
@gedeffe, @Korde-vaibhav and @walnut-tom 

Please check if the release `6.0.0-rc.1` works for you and give feedback, so that we know if we are on the good path for a `6.0.0` release.

I am closing this issue now.

If you need something more, please reopen this issue with exact details about what is missing. Or open a new one.
