### ISSUE TITLE
`EpicsApi` missing the ability to list epics using filters

### ISSUE THREAD

**Issue by hsebouai** [gitlab4j/gitlab4j-api#986]
Right now the `EpicApi` class does not have a method that accept some kind of `EpicFilter` that reflect the query parameters that are documented [here](https://docs.gitlab.com/ee/api/epics.html#list-epics-for-a-group)

Is there any plan to add that ability in the foreseeable future?

**Comment by jmini** [comment]
I guess this one is not included yet in the versions released this morning (`6.0.0-rc.2` and `5.3.0`).

I added quite a lot of Epic-related stuff, but I don't remember having added that.

**Comment by hsebouai** [comment]
Thank you for the latest release 5.3.0. 

I've checked it. and indeed there is no filter for epics yet.

**Comment by jmini** [comment]
Have a look at the PR https://github.com/gitlab4j/gitlab4j-api/pull/1005

---

You can use [jitpack](https://jitpack.io/) to test in advance,  as I did in my [EpicsScript.java](https://github.com/jmini/gitlab-experiments/blob/HEAD/epics/EpicsScript.java) script.

I created a tag in my fork in my fork: [5.3.0-jmini.3](https://github.com/jmini/gitlab4j-api/releases/tag/5.3.0-jmini.3), to test the PR and have a fixed version created by jitpack.

**Usage with gradle:**

```gradle
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
        content {
            includeGroup "com.github.jmini"
        }
    }
}

dependencies {
    // ...
    implementation 'com.github.jmini:gitlab4j-api:5.3.0-jmini.3'
    // ...
}
```

**Usage with maven:**

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.unblu</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>5.3.0-jmini.3</version>
  </dependency>
  <!-- ... -->
</dependencies>
```

**Usage with jbang:**

The example script uses [Jbang](https://www.jbang.dev/) where loading the dependency is really easy. You just need to declare this dependency:

```java
//DEPS https://github.com/jmini/gitlab4j-api/tree/5.3.0-jmini.3
```

Instead of:
```java
//DEPS org.gitlab4j:gitlab4j-api:5.2.0
```

And then Jbang does the work of adding the additional repository for you.

**Comment by jmini** [comment]
Have a look at the PR https://github.com/gitlab4j/gitlab4j-api/pull/1005

---

You can use [jitpack](https://jitpack.io/) to test in advance,  as I did in my [EpicsScript.java](https://github.com/jmini/gitlab-experiments/blob/HEAD/epics/EpicsScript.java) script.

I created a tag in my fork in my fork: [5.3.0-jmini.3](https://github.com/jmini/gitlab4j-api/releases/tag/5.3.0-jmini.3), to test the PR and have a fixed version created by jitpack.

**Usage with gradle:**

```gradle
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
        content {
            includeGroup "com.github.jmini"
        }
    }
}

dependencies {
    // ...
    implementation 'com.github.jmini:gitlab4j-api:5.3.0-jmini.3'
    // ...
}
```

**Usage with maven:**

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.unblu</groupId>
    <artifactId>gitlab4j-api</artifactId>
    <version>5.3.0-jmini.3</version>
  </dependency>
  <!-- ... -->
</dependencies>
```

**Usage with jbang:**

The example script uses [Jbang](https://www.jbang.dev/) where loading the dependency is really easy. You just need to declare this dependency:

```java
//DEPS https://github.com/jmini/gitlab4j-api/tree/5.3.0-jmini.3
```

Instead of:
```java
//DEPS org.gitlab4j:gitlab4j-api:5.2.0
```

And then Jbang does the work of adding the additional repository for you.

**Comment by hsebouai** [comment]
Thank you for this update, we will switch to the newest version as soon as this changed is merged.
